#!/usr/bin/python3

# system76-driver: Universal driver for System76 computers
# Copyright (C) 2005-2016 System76, Inc.
#
# This file is part of `system76-driver`.
#
# `system76-driver` is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# `system76-driver` is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with `system76-driver`; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import argparse
import os
from os import path
import sys
import logging

from system76driver.products import PRODUCTS
from system76driver.actions import ActionRunner
from system76driver.util import create_logs
from system76driver.model import determine_model_new

parser = argparse.ArgumentParser()
parser.add_argument('--strict', action='store_true', default=False,
    help='Exit with a non-zero status if not a valid system76 product',
)
parser.add_argument('--model', help='force model rather than detecting it')
parser.add_argument('--logs', help='Store logs to specified home directory')
parser.add_argument('--detect-model', action='store_true',
    help='Print the detected model without applying changes')
parser.add_argument('--dry', action='store_true',
    help='List required actions without applying changes')
args = parser.parse_args()
if args.dry and args.logs:
    parser.error('--dry cannot be combined with --logs')
exitcode = (2 if args.strict else 0)

# Because system76-driver-cli will be called automatically from the postinst
# script, we don't log to /var/log/system76-driver.log
logging.basicConfig(
    level=logging.DEBUG,
    format='%(levelname)s\t%(message)s',
)
log = logging.getLogger()

# This is a hack so that the driver doesn't get run in the VM when mastering
# and maintaining the golden images:
MARKER = '/var/cache/system76-pre-master.marker'
if path.exists(MARKER) and not (args.logs or args.detect_model):
    log.warning('Pre-master marker exists: %r', MARKER)
    sys.exit(0)


if os.getuid() != 0:
    log.error('must be run as root')
    sys.exit(1)

try:
    if args.detect_model:
        print(determine_model_new())
    elif args.logs is not None:
        tgz = create_logs(args.logs)
        log.info('logs stored in %s', tgz)
    else:
        product_version = args.model or determine_model_new()
        product = PRODUCTS.get(product_version)
        if product is None:
            log.warning('invalid product_version: %r', product_version)
            sys.exit(exitcode)
        log.info('product_version: %r', product_version)
        action_runner = ActionRunner(product['drivers'])
        for msg in action_runner.run_iter(dry=args.dry):
            log.info('* %s', msg)
except Exception:
    log.exception('Error running actions:')
    sys.exit(1)

